[project]
name = "polynews"
version = "0.1.0"
description = "Polymarket predictions tracker with price history"
requires-python = ">=3.11"
dependencies = [
    "google-genai>=1.45.0",
    "httpx>=0.27.0",
]

[project.optional-dependencies]
dev = [
    "python-dotenv>=1.1.1",
]
